//For Login Actiontypes
export const LOGIN_START = "LOGIN_START";
export const LOGIN_START_SUCCESS = "LOGIN_START_SUCCESS"; 
export const LOGIN_START_FAILURE = "LOGIN_START_FAILURE";

//Posting Add source or GROUPNAME  Actiontypes
export const POST_ROOT_GROUPNAME_START = "POST_ROOT_GROUPNAME_START";
export const POST_ROOT_GROUPNAME_SUCCESS = "POST_ROOT_GROUPNAME_SUCCESS"; 
export const POST_ROOT_GROUPNAME_FAILURE = "POST_ROOT_GROUPNAME_FAILURE";

//Get GROUPNAME Actiontypes
export const GET_ROOT_GROUPNAME_START = "GET_ROOT_GROUPNAME_START";
export const GET_ROOT_GROUPNAME_SUCCESS = "GET_ROOT_GROUPNAME_SUCCESS"; 
export const GET_ROOT_GROUPNAME_FAILURE = "GET_ROOT_GROUPNAME_FAILURE";
