//For Login Actiontypes
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS';
export const LOGIN_START_FAILURE = 'LOGIN_START_FAILURE';

//Posting Add source or GROUPNAME  Actiontypes
export const POST_ROOT_GROUPNAME_START = 'POST_ROOT_GROUPNAME_START';
export const POST_ROOT_GROUPNAME_SUCCESS = 'POST_ROOT_GROUPNAME_SUCCESS';
export const POST_ROOT_GROUPNAME_FAILURE = 'POST_ROOT_GROUPNAME_FAILURE';

//Get GROUPNAME Actiontypes
export const GET_ROOT_GROUPNAME_START = 'GET_ROOT_GROUPNAME_START';
export const GET_ROOT_GROUPNAME_SUCCESS = 'GET_ROOT_GROUPNAME_SUCCESS';
export const GET_ROOT_GROUPNAME_FAILURE = 'GET_ROOT_GROUPNAME_FAILURE';

//Post Categories Actiontypes
export const POST_CATEGORIES_START = 'POST_CATEGORIES_START';
export const POST_CATEGORIES_SUCCESS = 'POST_CATEGORIES_SUCCESS';
export const POST_CATEGORIES_FAILURE = 'POST_CATEGORIES_FAILURE';

//Get Categories Actiontypes
export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

//Post products Actiontypes
export const POST_PRODUCT_START = 'POST_PRODUCT_START';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';

//Get PRODUCT Actiontypes
export const GET_PRODUCT_START = 'GET_PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

//Upload product file 
export const UPLOAD_PRODUCT_FILE = 'UPLOAD_PRODUCT_FILE';
export const UPLOAD_PRODUCT_FILE_SUCCESS = 'UPLOAD_PRODUCT_FILE_SUCCESS';
export const UPLOAD_PRODUCT_FILE_FAILURE = 'UPLOAD_PRODUCT_FILE_FAILURE';
